version: '3.8'

services:
  avito-shop-service:
    build:
      context: .  # Путь к директории с исходниками
    container_name: avito-shop-service
    ports:
      - "8080:8080"
    env_file:
      - .env.local
    environment:
      # переменные окружения для подключения к БД
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=shop
      - DATABASE_HOST=db
      # порт сервиса
      - SERVER_PORT=8080
    depends_on:
      db:
        condition: service_healthy
    networks:
      - internal

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d  # Монтирование всей директории миграций
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U postgres -d shop'" ]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - internal

networks:
  internal:


# FROM golang:1.22.3 AS builder
# WORKDIR /avito-shop
# COPY . .
# RUN go mod tidy
# RUN go build -o ./bin/main cmd/main.go
# RUN chmod +x ./bin/main
# EXPOSE 8080
# CMD ["./bin/main"]
